version: '3'

tasks:
  check:
    deps: [backend:check, frontend:check]

  deploy:
    cmds:
      - docker compose up --build -d

  down:
    cmds:
      - docker compose down

  backend:lint:
    dir: backend
    cmds:
      - ruff check .

  backend:typecheck:
    dir: backend
    cmds:
      - mypy main.py

  backend:test:
    dir: backend
    cmds:
      - pytest -v

  backend:check:
    deps: [backend:lint, backend:typecheck, backend:test]

  frontend:lint:
    dir: frontend
    cmds:
      - npm run lint

  frontend:typecheck:
    dir: frontend
    cmds:
      - npm run type-check

  frontend:test:
    dir: frontend
    cmds:
      - npm run test

  frontend:check:
    deps: [frontend:lint, frontend:typecheck, frontend:test]

  default:
    deps: [check]
