"""Multi-agent travel planning — powered by DeepSeek LLM.

All destination knowledge is generated by the LLM at runtime.
No hardcoded data — the model knows the world.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timedelta
from typing import Any

from llm import chat, chat_json
from models import DayPlan, TravelPlan, TravelPlanRequest

# ── Prompts ─────────────────────────────────────────────────────

PLANNER_SYSTEM = """\
你是一个资深的旅行规划专家。根据用户的需求，制定详细、可行的每日行程。

输出 JSON：
{
  "overview": "旅行概览（2-3句）",
  "weather_summary": "旅行期间天气概况（根据常识推测）",
  "weather_forecast": [
    {"date": "YYYY-MM-DD", "condition": "晴/多云/雨等",
     "temperature_high": 25, "temperature_low": 15,
     "humidity": 60, "precipitation": 10,
     "icon": "sunny/cloudy/rainy", "tips": "当日天气贴士"}
  ],
  "days": [
    {
      "day": 1,
      "theme": "当日主题",
      "activities": [
        {"time": "09:00", "name": "景点中文名", "name_en": "English",
         "duration": "2-3小时", "note": "贴士", "category": "分类",
         "ticket": "¥50或免费"}
      ],
      "meals": [
        {"type": "早餐", "time": "08:00",
         "suggestion": "具体菜品+餐厅类型", "budget": 50}
      ],
      "transportation": "交通建议",
      "notes": "备注"
    }
  ],
  "tips": ["贴士1", "贴士2"],
  "attractions": [
    {"id": "a1", "name": "英文名", "name_cn": "中文名",
     "description": "简介", "category": "分类", "rating": 4.5,
     "suggested_duration": "2-3小时", "ticket_price": 0,
     "image_url": "", "tips": "贴士"}
  ],
  "hotels": [
    {"id": "h1", "name": "英文名", "name_cn": "中文名",
     "description": "简介", "star_rating": 4, "price_per_night": 800,
     "location": "位置", "amenities": ["WiFi", "早餐"],
     "image_url": ""}
  ],
  "budget_breakdown": {
    "交通(含机票)": 3000, "住宿": 2000, "餐饮": 1500,
    "门票/活动": 500, "购物": 1000, "其他/应急": 1000
  }
}

规则：
- 根据常识推测合理的天气、景点、酒店
- 每天 1-3 个景点，节奏合理
- 餐饮要具体（菜名+餐厅类型）
- 门票用当地货币或人民币
- 酒店价格合理
- 旅游旺季/淡季体现在价格中"""

COMPANION_SYSTEM = """\
你是旅行AI伴侣"小旅"。热情、具体、实用。
回复JSON: {"reply":"回复(≤150字)","suggestions":["建议1","建议2","建议3"],
"agent_emoji":"🍜/🚗/🌤️/🗣️/📸/🆘/🤖"}"""

BLOG_SYSTEM = """\
你是旅行作家。根据行程写游记。JSON:
{"title":"标题","summary":"摘要","content":"Markdown游记",
"tags":["tag"],"suggested_hashtags":["#tag"],
"cover_description":"封面描述"}"""


# ── Plan ────────────────────────────────────────────────────────

def plan_travel(request: TravelPlanRequest) -> TravelPlan:
    """Multi-agent workflow — all knowledge from LLM."""
    plan_id = str(uuid.uuid4())[:8]
    log: list[str] = []
    days_cnt = (request.end_date - request.start_date).days + 1

    # Phase 1: Scout — quick destination briefing
    log.append("[ScoutAgent] 调研目的地...")
    scout = chat(
        system="你是目的地调研专家。用3句话介绍这个城市的核心亮点、最佳季节、必体验。",
        user=f"介绍{request.destination}（{days_cnt}天旅行，{request.style}风格）",
        max_tokens=512,
    )
    log.append(f"[ScoutAgent] {scout[:120]}...")

    # Phase 2+3+4: Planner does everything (weather + itinerary + tips)
    log.append("[PlannerAgent] 生成行程/天气/景点/酒店...")
    user = f"""目的地: {request.destination}
出发: {request.departure_city}
日期: {request.start_date} ~ {request.end_date}（{days_cnt}天）
预算: ¥{request.budget:,.0f} | {request.travelers}人
风格: {request.style}
兴趣: {', '.join(request.interests) if request.interests else '无'}
特殊需求: {request.special_requirements or '无'}"""

    try:
        data = chat_json(PLANNER_SYSTEM, user, temperature=0.7, max_tokens=8192)
        log.append("[PlannerAgent] 生成完成")
    except Exception as e:
        log.append(f"[PlannerAgent] 失败: {e}")
        data = {"overview": f"{request.destination}之旅", "days": [], "tips": [],
                "weather_forecast": [], "attractions": [], "hotels": [],
                "budget_breakdown": {}, "weather_summary": ""}

    # Phase 5: Budget review
    log.append("[BudgetAgent] 审核预算...")
    bd = data.get("budget_breakdown", {})
    total = sum(float(v) for v in bd.values()) if bd else 0
    if total > 0:
        log.append(f"[BudgetAgent] 预估 ¥{total:,.0f} "
                   f"{'超预算' if total > request.budget else '预算内'}")
    else:
        log.append("[BudgetAgent] 待定")

    # Build result
    days: list[DayPlan] = []
    for d in data.get("days", []):
        days.append(DayPlan(
            day=d.get("day", len(days) + 1),
            date=request.start_date + timedelta(days=d.get("day", len(days) + 1) - 1),
            theme=d.get("theme", "探索日"),
            activities=d.get("activities", []),
            meals=d.get("meals", []),
            transportation=d.get("transportation", ""),
            notes=d.get("notes", ""),
        ))

    tips = data.get("tips", [])
    if request.special_requirements:
        tips.insert(0, f"已针对「{request.special_requirements}」优化")

    overview = data.get("overview", f"{request.destination}{days_cnt}天之旅")

    n_acts = sum(len(d.activities) for d in days)
    log.append(f"[Synthesizer] {len(days)}天 {n_acts}景点")

    return TravelPlan(
        id=plan_id,
        created_at=datetime.now(),
        request=request,
        overview=overview,
        weather_forecast=data.get("weather_forecast", []),
        days=days,
        budget_breakdown=bd,
        tips=tips,
        recommended_attractions=data.get("attractions", []),
        recommended_hotels=data.get("hotels", []),
        agent_log=log,
    )


# ── Companion ───────────────────────────────────────────────────

def companion_chat(
    message: str, context: dict[str, Any] | None = None,
) -> dict[str, Any]:
    ctx = context or {}
    prefix = ""
    if ctx.get("destination"):
        prefix = f"[用户在{ctx['destination']}旅行中] "
    result: dict[str, Any] = chat_json(
        COMPANION_SYSTEM, prefix + message, temperature=0.8, max_tokens=1024,
    )
    result["relevant_info"] = ctx
    return result


# ── Blog ────────────────────────────────────────────────────────

def generate_blog(plan: TravelPlan | None, tone: str, focus: str) -> dict[str, Any]:
    if plan is None:
        return {"title": "旅行日记", "summary": "", "content": "", "tags": [],
                "suggested_hashtags": [], "cover_description": ""}

    days_txt = ""
    for d in plan.days:
        days_txt += f"Day {d.day} {d.theme}: "
        for a in d.activities:
            days_txt += f"{a.get('time','')} {a.get('name','')}; "
        days_txt += "\n"

    tone_map = {
        "casual": "轻松口语化", "formal": "精致散文",
        "poetic": "诗意浪漫", "humorous": "幽默段子",
    }
    result: dict[str, Any] = chat_json(
        BLOG_SYSTEM,
        f"目的地:{plan.request.destination} | 风格:{tone_map.get(tone, tone)} | "
        f"重点:{focus}\n行程:\n{days_txt}\n预算:{plan.budget_breakdown}",
        temperature=0.8, max_tokens=8192,
    )
    return result
