<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { api, type Trip } from '@/services/api'

const trips = ref<Trip[]>([]); const tripId = ref<number | null>(null); const message = ref(''); const loading = ref(false); const locationEnabled = ref(false); const locationText = ref('尚未获取位置'); const error = ref('')
const messages = ref([{ role: 'agent', text: '你好，我是 Hikari。选择一趟行程后，可以问我行程中的任何问题。' }])
async function loadTrips() { try { trips.value = await api.listTrips(); tripId.value = trips.value[0]?.id || null } catch (cause) { error.value = cause instanceof Error ? cause.message : '无法读取行程。' } }
async function send() { const text = message.value.trim(); if (!text) return; if (!tripId.value) { error.value = '请先创建并选择一趟行程。'; return }; error.value = ''; messages.value.push({ role: 'user', text }); message.value = ''; loading.value = true; try { const reply = await api.sendChatMessage({ trip_id: tripId.value, message: text, location_name: locationEnabled.value ? locationText.value : undefined }); messages.value.push({ role: 'agent', text: reply.reply || reply.content || '已收到你的问题。' }) } catch (cause) { error.value = cause instanceof Error ? cause.message : '暂时无法获取回复。' } finally { loading.value = false } }
function locate() { if (!globalThis.navigator.geolocation) { error.value = '当前浏览器不支持定位。'; return }; globalThis.navigator.geolocation.getCurrentPosition(async (position) => { try { await api.updateLocation({ latitude: position.coords.latitude, longitude: position.coords.longitude, location_context: '浏览器实时定位' }); locationEnabled.value = true; locationText.value = `${position.coords.latitude.toFixed(4)}, ${position.coords.longitude.toFixed(4)}` } catch (cause) { error.value = cause instanceof Error ? cause.message : '位置上传失败。' } }, () => { error.value = '未能获取定位权限。' }) }
onMounted(loadTrips)
</script>

<template><div class="page companion-page"><section class="hero"><p class="eyebrow">TRAVEL COMPANION · HIKARI</p><h1>旅程在发生，建议也应及时抵达。</h1><p>基于已保存的行程、你的问题和当前位置，获得后端陪伴接口的实时回复。</p></section><div class="grid"><section class="card chat"><div class="chat-head"><div><span>✦</span><b>Hikari · 旅行陪伴</b><small>已连接聊天与定位接口</small></div><em>● 在线</em></div><div class="trip-select"><label>当前行程<select v-model="tripId"><option :value="null">请选择行程</option><option v-for="trip in trips" :key="trip.id" :value="trip.id">{{ trip.destination_city }} · {{ trip.title }}</option></select></label></div><div class="messages"><div v-for="(item, index) in messages" :key="index" class="message" :class="item.role">{{ item.text }}</div></div><div class="quick"><button v-for="ask in ['附近有什么值得去？', '今天需要带伞吗？', '帮我调整下午安排']" :key="ask" @click="message = ask; send()">{{ ask }}</button></div><form class="composer" @submit.prevent="send"><input v-model="message" :disabled="loading" placeholder="问问 Hikari…"><button :disabled="loading">{{ loading ? '发送中' : '发送' }}</button></form><p v-if="error" class="error">{{ error }}</p></section><aside><section class="card context"><span>⌖</span><h2>{{ locationEnabled ? '位置已同步' : '尚未获取位置' }}</h2><p>{{ locationEnabled ? locationText : '授权后会将经纬度同步到后端，用于对话时提供当前位置上下文。' }}</p><button class="secondary" @click="locate">{{ locationEnabled ? '更新位置' : '开启定位' }}</button></section><section class="card guide"><p class="eyebrow">HOW IT WORKS</p><h2>真实行程上下文</h2><p>该页面只使用现有的行程、聊天和定位接口；没有额外虚构的推荐或社区能力。</p></section></aside></div></div></template>

<style scoped>
.companion-page{max-width:1180px;margin:auto;padding:42px 26px 70px}.hero{margin-bottom:26px;padding:30px 35px;border:1px solid #dcebdd;border-radius:24px;background:linear-gradient(115deg,#fff,#eef9f1)}.eyebrow{margin:0 0 9px;color:#579379;letter-spacing:.13em;font-size:11px;font-weight:700}.hero h1{margin:0;color:#254838;font:700 clamp(28px,4vw,40px)/1.3 'Noto Serif SC','Microsoft YaHei',serif}.hero p:last-child{color:#728178;line-height:1.75}.grid{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:22px}.card{border:1px solid #e0e9e2;border-radius:18px;background:#fff;box-shadow:0 10px 28px rgba(39,91,66,.06)}.chat{overflow:hidden}.chat-head{display:flex;justify-content:space-between;align-items:center;padding:17px 20px;border-bottom:1px solid #edf2ee}.chat-head div{display:grid;grid-template-columns:34px auto;column-gap:9px;align-items:center}.chat-head span{grid-row:span 2;display:grid;place-items:center;width:33px;height:33px;border-radius:10px;background:#2f8869;color:white}.chat-head b{font-size:14px}.chat-head small{color:#829087;font-size:11px}.chat-head em{color:#318968;font-size:11px;font-style:normal}.trip-select{padding:12px 18px;background:#f8fbf8}.trip-select label{display:grid;grid-template-columns:72px 1fr;align-items:center;gap:8px;color:#66776d;font-size:12px;font-weight:700}.trip-select select{padding:8px;border:1px solid #dfe9e1;border-radius:8px;background:#fff;color:#3e554b}.messages{display:flex;min-height:330px;flex-direction:column;gap:12px;padding:20px;background:linear-gradient(145deg,#fff,#fafcf9)}.message{max-width:76%;padding:11px 13px;border-radius:12px;line-height:1.6;font-size:14px}.agent{align-self:start;background:#ebf7f0;color:#3f5e51}.user{align-self:end;background:#2c8769;color:#fff}.quick{display:flex;gap:7px;flex-wrap:wrap;padding:11px 16px}.quick button{border:1px solid #dfebe2;border-radius:14px;padding:6px 9px;background:#f8fbf8;color:#55766a;font-size:11px;cursor:pointer}.composer{display:flex;gap:8px;padding:13px 16px;border-top:1px solid #edf2ee}.composer input{flex:1;border:1px solid #dfe9e1;border-radius:9px;padding:10px;outline:none}.composer button,.secondary{border:0;border-radius:9px;padding:10px 14px;background:#2c775b;color:#fff;font-weight:700;cursor:pointer}.error{padding:0 16px 13px;margin:0;color:#b64b4b;font-size:12px}aside{display:grid;align-content:start;gap:18px}.context,.guide{padding:23px}.context>span{color:#2d8c6b;font-size:25px}.context h2,.guide h2{margin:9px 0;color:#315044;font-size:18px}.context p,.guide p{color:#75837b;font-size:13px;line-height:1.75}.guide{background:#f4faf5}@media(max-width:760px){.companion-page{padding:26px 16px}.hero{padding:26px 22px}.grid{grid-template-columns:1fr}.messages{min-height:250px}}
</style>
