<script setup lang="ts">
import { ref } from 'vue'

const message = ref(''); const messages = ref([{ role: 'agent', text: '你好，我是 Hikari。告诉我你现在在哪里，或直接问我旅行中的任何问题。' }]); const locationEnabled = ref(false)
function send() { if (!message.value.trim()) return; messages.value.push({ role: 'user', text: message.value.trim() }); const question = message.value.trim(); message.value = ''; globalThis.setTimeout(() => messages.value.push({ role: 'agent', text: `已记录：「${question}」。实时陪伴 Agent 的后端接口正在接入中；目前页面已预留对话、定位和情境建议入口。` }), 350) }
function locate() { if (!globalThis.navigator.geolocation) return; globalThis.navigator.geolocation.getCurrentPosition(() => { locationEnabled.value = true }, () => { locationEnabled.value = false }) }
</script>

<template>
  <div class="page companion-page"><section class="companion-hero"><p class="eyebrow">Travel companion · Hikari</p><h1 class="page-title">旅程在发生，建议也该及时抵达。</h1><p class="page-intro">根据你的位置、时间和当下状态，给出刚刚好的下一步。</p></section>
    <div class="companion-grid"><section class="card chat-card"><div class="chat-header"><div><span class="hikari">✦</span><b>Hikari · 旅行陪伴</b><small>轻量实时建议</small></div><span class="online">● 在线</span></div><div class="messages"><div v-for="(item,index) in messages" :key="index" class="message" :class="item.role">{{ item.text }}</div></div><div class="quick-asks"><button v-for="ask in ['附近有什么值得去？','今天需要带伞吗？','帮我找一家餐厅']" :key="ask" @click="message=ask;send()">{{ ask }}</button></div><form class="composer" @submit.prevent="send"><input v-model="message" placeholder="问问 Hikari…" /><button type="submit">发送</button></form></section>
      <aside class="companion-side"><section class="card context-card"><span class="pin">⌖</span><h2>{{ locationEnabled ? '已开启位置' : '尚未获取位置' }}</h2><p>{{ locationEnabled ? 'Hikari 将据此调整附近推荐。' : '开启位置后，获得附近景点、餐饮和路线建议。' }}</p><button class="secondary-button" @click="locate">{{ locationEnabled ? '更新位置' : '开启定位' }}</button></section><section class="card future-card"><p class="eyebrow">Coming next</p><h2>动态改线</h2><p>天气、闭馆、排队和交通延误触发行程调整。</p><span>接口预留中</span></section></aside>
    </div>
    <section class="companion-signals"><div class="signal-heading"><p class="eyebrow">Signals around you</p><h2>出发前，Hikari 会关注这些变化</h2><p>以下模块已按需求文档预留展示位置；数据接入后将基于当前地点、时间与行程自动更新。</p></div><div class="signal-grid"><article class="card"><span>☼</span><b>天气变化</b><small>降雨、体感温度与穿衣建议</small><em>等待 MCP 天气数据</em></article><article class="card"><span>↗</span><b>交通与步行</b><small>拥堵、通勤时长和替代路线</small><em>等待 MCP 路线数据</em></article><article class="card"><span>⌁</span><b>附近灵感</b><small>景点、餐厅与可休息的去处</small><em>开启定位后可用</em></article></div></section>
  </div>
</template>

<style scoped>
.companion-hero{margin-bottom:32px}.companion-grid{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:22px}.chat-card{overflow:hidden}.chat-header{padding:17px 20px;border-bottom:1px solid #edf1ed;display:flex;justify-content:space-between;align-items:center}.chat-header>div{display:grid;grid-template-columns:33px auto;column-gap:9px;align-items:center}.chat-header b{font-size:14px}.chat-header small{font-size:11px;color:#84918b}.hikari{grid-row:span 2;display:grid;place-items:center;width:32px;height:32px;color:#fff;border-radius:10px;background:linear-gradient(135deg,#24997b,#91d3a6)}.online{font-size:11px;color:#2d9b7b}.messages{min-height:355px;padding:21px;display:flex;flex-direction:column;gap:13px;background:linear-gradient(145deg,#fff,#fafcf9)}.message{max-width:74%;padding:11px 13px;border-radius:12px;font-size:14px;line-height:1.6}.message.agent{background:#edf8f2;color:#3d5f52;border-bottom-left-radius:3px}.message.user{margin-left:auto;background:#298d71;color:#fff;border-bottom-right-radius:3px}.quick-asks{padding:10px 16px;display:flex;gap:7px;flex-wrap:wrap}.quick-asks button{font-size:11px;padding:6px 8px;color:#52766a;background:#f7faf7;border:1px solid #e1e9e3;border-radius:14px}.composer{border-top:1px solid #edf1ed;display:flex;gap:8px;padding:13px 16px}.composer input{margin:0}.composer button{border:0;border-radius:8px;color:#fff;background:#258b70;padding:0 15px}.companion-side{display:grid;align-content:start;gap:18px}.context-card,.future-card{padding:23px}.pin{color:#309a7d;font-size:24px}.context-card h2,.future-card h2{font-size:17px;margin:10px 0 6px}.context-card p,.future-card p{font-size:13px;line-height:1.7;color:#75827c;margin:0 0 16px}.future-card{background:linear-gradient(145deg,#fbfefb,#f0f8f3)}.future-card span{font-size:11px;color:#4b9d82;background:#ddf2e6;padding:5px 8px;border-radius:10px}@media(max-width:760px){.companion-grid{grid-template-columns:1fr}.messages{min-height:280px}}
</style>

<style scoped>
.companion-signals { display: grid; grid-template-columns: 285px 1fr; gap: 22px; align-items: center; margin-top: 28px; padding: 25px; border: 1px solid #dce9df; border-radius: 20px; background: rgba(255,255,255,.66); }.signal-heading h2 { margin: 7px 0; color: #254337; font: 700 20px/1.4 'Noto Serif SC','Microsoft YaHei',serif; }.signal-heading p:last-child { margin: 0; color: #78847e; font-size: 12px; line-height: 1.7; }.signal-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; }.signal-grid article { min-height: 140px; padding: 16px; border-radius: 14px; }.signal-grid span { display: grid; width: 31px; height: 31px; place-items: center; border-radius: 9px; color: #248d70; background: #e7f6ed; }.signal-grid b, .signal-grid small, .signal-grid em { display: block; }.signal-grid b { margin-top: 12px; color: #3b554a; font-size: 13px; }.signal-grid small { margin-top: 4px; color: #85928b; font-size: 11px; line-height: 1.5; }.signal-grid em { margin-top: 10px; color: #57927d; font-size: 10px; font-style: normal; } @media(max-width:850px){.companion-signals{grid-template-columns:1fr}.signal-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.companion-signals{padding:20px 16px}.signal-grid{grid-template-columns:1fr}.signal-grid article{min-height:0}}
</style>
