<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { api, type Advice, type Itinerary, type Memo, type Trip } from '@/services/api'

const trips = ref<Trip[]>([]); const tripId = ref<number | null>(null); const messages = ref([{ role: 'agent', text: '你好，我是 Hikari。选择一趟行程后，我可以结合实时行程为你提供建议。' }]); const message = ref(''); const error = ref(''); const loading = ref(false)
const memos = ref<Memo[]>([]); const itineraries = ref<Itinerary[]>([]); const advice = ref<Advice[]>([]); const memoText = ref(''); const adviceReason = ref(''); const itinerary = ref({ title: '', place_name: '', start_time: '', end_time: '', itinerary_type: 'play' as 'play' | 'transit' })

async function loadWorkspace() { if (!tripId.value) return; try { [memos.value, itineraries.value, advice.value] = await Promise.all([api.listMemos(tripId.value), api.listItineraries(tripId.value), api.listAdvice(tripId.value)]) } catch (cause) { error.value = cause instanceof Error ? cause.message : '无法读取旅途中数据。' } }
async function loadTrips() { try { trips.value = await api.listTrips(); tripId.value = trips.value[0]?.id || null } catch (cause) { error.value = cause instanceof Error ? cause.message : '无法读取行程。' } }
function stripThink(text: string) { return text.replace(/<think>[\s\S]*?<\/think>/gi, '').trim() }
async function send() { const text = message.value.trim(); if (!text || !tripId.value) return; messages.value.push({ role: 'user', text }); message.value = ''; loading.value = true; try { const reply = await api.sendChatMessage({ trip_id: tripId.value, message: text }); messages.value.push({ role: 'agent', text: stripThink(reply.reply) }) } catch (cause) { error.value = cause instanceof Error ? cause.message : '暂时无法获取回复。' } finally { loading.value = false } }
async function addMemo() { if (!tripId.value || !memoText.value.trim()) return; try { memos.value.unshift(await api.createMemo({ trip_id: tripId.value, memo_text: memoText.value.trim() })); memoText.value = '' } catch (cause) { error.value = cause instanceof Error ? cause.message : '备忘录保存失败。' } }
async function removeMemo(id: number) { try { await api.deleteMemo(id); memos.value = memos.value.filter((item) => item.memo_id !== id) } catch (cause) { error.value = cause instanceof Error ? cause.message : '删除失败。' } }
async function addItinerary() { if (!tripId.value || !itinerary.value.title || !itinerary.value.place_name || !itinerary.value.start_time || !itinerary.value.end_time) return; try { itineraries.value.push(await api.createItinerary({ trip_id: tripId.value, ...itinerary.value, start_time: new Date(itinerary.value.start_time).toISOString(), end_time: new Date(itinerary.value.end_time).toISOString(), status: 'pending', is_initial: false, reminder_time: null })); itinerary.value = { title: '', place_name: '', start_time: '', end_time: '', itinerary_type: 'play' } } catch (cause) { error.value = cause instanceof Error ? cause.message : '日程保存失败。' } }
async function removeItinerary(id: number) { try { await api.deleteItinerary(id); itineraries.value = itineraries.value.filter((item) => item.itinerary_id !== id) } catch (cause) { error.value = cause instanceof Error ? cause.message : '删除失败。' } }
async function requestAdvice() { if (!tripId.value || !adviceReason.value.trim()) return; loading.value = true; try { advice.value.unshift(await api.generateAdvice({ trip_id: tripId.value, reason: adviceReason.value.trim(), current_itinerary: itineraries.value })); adviceReason.value = '' } catch (cause) { error.value = cause instanceof Error ? cause.message : '暂时无法生成调整建议。' } finally { loading.value = false } }
async function act(adviceId: number, action: 'accept' | 'reject') { try { const updated = await api.actOnAdvice(adviceId, action); advice.value = advice.value.map((item) => item.advice_id === adviceId ? updated : item) } catch (cause) { error.value = cause instanceof Error ? cause.message : '操作失败。' } }
watch(tripId, loadWorkspace); onMounted(loadTrips)
</script>

<template><div class="page companion-page"><section class="hero"><p class="eyebrow">TRAVEL COMPANION · HIKARI</p><h1>旅程在发生，建议也应及时抵达。</h1><p>对话、备忘、实时日程和调整建议都与同一趟行程关联。</p></section><p v-if="error" class="error">{{ error }}</p><div class="trip-bar"><label>当前行程<select v-model="tripId"><option :value="null">请选择行程</option><option v-for="trip in trips" :key="trip.id" :value="trip.id">{{ trip.destination_city }} · {{ trip.title }}</option></select></label></div><div class="main-grid"><section class="card chat"><div class="messages"><div v-for="(item, index) in messages" :key="index" class="message" :class="item.role">{{ item.text }}</div></div><form class="composer" @submit.prevent="send"><input v-model="message" :disabled="loading || !tripId" placeholder="问问 Hikari…"><button :disabled="loading || !tripId">发送</button></form></section><aside class="card advice"><h2>调整建议</h2><div class="inline-form"><input v-model="adviceReason" placeholder="如：下雨了，想调整下午安排"><button @click="requestAdvice">生成</button></div><article v-for="item in advice.slice(0, 3)" :key="item.advice_id"><p>{{ item.advice_text }}</p><div v-if="item.result === 'pending' || item.result === 'revising'"><button @click="act(item.advice_id, 'accept')">采纳</button><button class="quiet" @click="act(item.advice_id, 'reject')">忽略</button></div></article><p v-if="!advice.length" class="muted">输入变化原因后获取 AI 调整建议。</p></aside></div><div class="tool-grid"><section class="card tool"><h2>旅途备忘</h2><div class="inline-form"><input v-model="memoText" placeholder="记下一件要做的事"><button @click="addMemo">添加</button></div><div v-for="item in memos" :key="item.memo_id" class="row"><span>{{ item.memo_text }}</span><button class="icon" @click="removeMemo(item.memo_id)">×</button></div><p v-if="!memos.length" class="muted">暂无备忘。</p></section><section class="card tool"><h2>实时日程</h2><div class="schedule-form"><input v-model="itinerary.title" placeholder="事项名称"><input v-model="itinerary.place_name" placeholder="地点"><input v-model="itinerary.start_time" type="datetime-local"><input v-model="itinerary.end_time" type="datetime-local"><select v-model="itinerary.itinerary_type"><option value="play">游玩</option><option value="transit">交通</option></select><button @click="addItinerary">添加日程</button></div><div v-for="item in itineraries" :key="item.itinerary_id" class="row"><span><b>{{ item.title }}</b> · {{ item.place_name }}</span><button class="icon" @click="removeItinerary(item.itinerary_id)">×</button></div><p v-if="!itineraries.length" class="muted">暂无实时日程。</p></section></div></div></template>

<style scoped>
.companion-page{max-width:1180px;margin:auto;padding:42px 26px 70px}.hero{margin-bottom:18px;padding:30px 35px;border:1px solid #dcebdd;border-radius:24px;background:linear-gradient(115deg,#fff,#eef9f1)}.eyebrow{margin:0 0 9px;color:#579379;letter-spacing:.13em;font-size:11px;font-weight:700}.hero h1{margin:0;color:#254838;font:700 clamp(28px,4vw,40px)/1.3 'Noto Serif SC','Microsoft YaHei',serif}.hero p:last-child,.muted{color:#728178;font-size:13px;line-height:1.7}.error{color:#ad4d4d;font-size:13px}.trip-bar{margin-bottom:17px}.trip-bar label{display:flex;align-items:center;gap:10px;color:#52675c;font-size:13px;font-weight:700}.trip-bar select{min-width:240px;border:1px solid #dce8df;border-radius:9px;padding:9px;background:#fff}.main-grid{display:grid;grid-template-columns:minmax(0,1fr) 350px;gap:18px}.card{border:1px solid #e0e9e2;border-radius:18px;background:#fff;box-shadow:0 10px 28px rgba(39,91,66,.06)}.chat{overflow:hidden}.messages{display:flex;min-height:310px;flex-direction:column;gap:11px;padding:20px}.message{max-width:78%;padding:10px 12px;border-radius:11px;font-size:14px;line-height:1.6}.agent{align-self:flex-start;background:#ecf7f0;color:#3e5e51}.user{align-self:flex-end;background:#2b8668;color:#fff}.composer,.inline-form{display:flex;gap:8px;padding:12px;border-top:1px solid #edf2ee}.composer input,.inline-form input,.schedule-form input,.schedule-form select{min-width:0;flex:1;border:1px solid #dfe9e1;border-radius:8px;padding:9px;outline:none}.composer button,.inline-form button,.schedule-form button,.advice button{border:0;border-radius:8px;padding:9px 12px;background:#2c775b;color:#fff;font-weight:700;cursor:pointer}.advice,.tool{padding:19px}.advice h2,.tool h2{margin:0 0 12px;color:#315044;font-size:17px}.advice .inline-form{padding:0 0 12px}.advice article{margin-top:10px;padding:11px;border-radius:10px;background:#f5faf6}.advice article p{margin:0 0 9px;color:#456055;font-size:13px;line-height:1.65}.advice .quiet{margin-left:7px;background:#e9efeb;color:#5e7066}.tool-grid{display:grid;grid-template-columns:1fr 1.25fr;gap:18px;margin-top:18px}.row{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid #edf2ee;color:#4b6358;font-size:13px}.row b{color:#315447}.icon{border:0;background:transparent;color:#a65858;font-size:20px;cursor:pointer}.schedule-form{display:grid;grid-template-columns:1fr 1fr;gap:8px}.schedule-form button{grid-column:span 2}@media(max-width:760px){.companion-page{padding:26px 16px}.main-grid,.tool-grid{grid-template-columns:1fr}.trip-bar label{display:grid}.schedule-form{grid-template-columns:1fr}.schedule-form button{grid-column:auto}}
</style>
