<script setup lang="ts">
import { computed, ref } from 'vue'
import CommunityCard from '@/components/CommunityCard.vue'
import { searchCommunityPosts, type CommunityContentType } from '@/services/community'

const query = ref(''); const contentType = ref<'all' | CommunityContentType>('all'); const searched = ref(false)
const results = computed(() => searchCommunityPosts(query.value, contentType.value))
function search() { searched.value = true }
</script>

<template>
  <div class="page search-page"><section class="search-hero"><p class="eyebrow">Search the community</p><h1 class="page-title">去找一段，刚好打动你的旅程。</h1><form @submit.prevent="search"><input v-model="query" autofocus placeholder="搜索城市、玩法、主题或作者" /><button class="primary-button" type="submit">⌕ 搜索</button></form><div class="suggestions"><span>试试：</span><button v-for="tag in ['杭州','美食','城市漫游','云南']" :key="tag" type="button" @click="query=tag;search()">{{ tag }}</button></div></section><section class="search-options"><span>内容类型</span><label><input v-model="contentType" value="all" type="radio" /> 全部</label><label><input v-model="contentType" value="plan" type="radio" /> 行程</label><label><input v-model="contentType" value="blog" type="radio" /> 游记</label></section><section v-if="searched || query" class="result-area"><p class="result-count">找到 {{ results.length }} 条与「{{ query || '全部内容' }}」相关的内容</p><div v-if="results.length" class="post-grid"><CommunityCard v-for="post in results" :key="post.id" :post="post" /></div><div v-else class="empty-state card">没有找到结果。你也可以换一种说法，例如输入「慢旅行」或「周末」。</div></section><section v-else class="search-tips"><article><span>⌖</span><b>按目的地找</b><p>从一座想去的城市开始。</p></article><article><span>✦</span><b>按玩法找</b><p>美食、亲子、徒步、摄影或慢旅行。</p></article><article><span>✎</span><b>按故事找</b><p>看看其他旅行者如何记录瞬间。</p></article></section></div>
</template>

<style scoped>
.search-hero { padding: 48px 30px; text-align: center; border: 1px solid #dcebdd; border-radius: 23px; background: radial-gradient(circle at 50% 100%,#dff2e5,transparent 49%),linear-gradient(160deg,#fff,#f2faf4); }.search-hero .page-title { font-size: 34px; }.search-hero form { display: flex; max-width: 620px; gap: 9px; margin: 24px auto 13px; }.search-hero input { flex: 1; min-width: 0; padding: 13px 15px; border: 1px solid #cfe4d7; border-radius: 11px; outline: none; background: #fff; }.search-hero input:focus { border-color: #64b698; box-shadow: 0 0 0 4px #e4f5ea; }.suggestions { color: #829088; font-size: 11px; }.suggestions button { margin-left: 7px; padding: 3px 7px; border: 0; border-radius: 9px; color: #548070; background: #eaf6ee; font-size: 11px; }.search-options { display: flex; align-items: center; gap: 18px; margin: 22px 0; padding: 13px 16px; border: 1px solid #e0ebe3; border-radius: 12px; background: rgba(255,255,255,.78); color: #687970; font-size: 12px; }.search-options span { color: #3d594d; font-weight: 700; }.search-options input { accent-color: #218668; }.result-count { color: #728078; font-size: 13px; }.post-grid { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 17px; }.search-tips { display: grid; grid-template-columns: repeat(3,1fr); gap: 15px; margin-top: 26px; }.search-tips article { padding: 21px; border: 1px solid #e0ebe3; border-radius: 15px; background: rgba(255,255,255,.74); }.search-tips span { color: #249178; font-size: 21px; }.search-tips b,.search-tips p { display: block; }.search-tips b { margin-top: 10px; color: #3b5449; font-size: 14px; }.search-tips p { margin: 5px 0 0; color: #839088; font-size: 12px; }@media(max-width:650px){.search-hero{padding:36px 16px}.search-hero .page-title{font-size:29px}.search-hero form{flex-direction:column}.search-options{flex-wrap:wrap;gap:10px}.post-grid,.search-tips{grid-template-columns:1fr}}
</style>
